# -*- coding: utf-8 -*-
"""source_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxKu9-0idbWFAA2JCKWS9boeY6G71tuM
"""

!pip install -q google-generativeai

import google.generativeai as genai
import os

GOOGLE_API_KEY = "AIzaSyBTJubPmR0RZiPG-FtK0XPezGwyye7FKAY"
genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel('gemini-pro')

def explain_code(code: str, question: str):
    prompt = (
        "You are a helpful AI coding tutor.\n\n"
        "Here is a piece of code:\n"
        f"```python\n{code}\n```\n\n"
        f'The student has asked: "{question}"\n\n'
        "Please explain the code and answer the question in beginner-friendly terms. "
        "Mention DSA concepts if relevant, and avoid jargon."
    )

    response = model.generate_content(prompt)

    # Return response safely based on object structure
    return response.text if hasattr(response, 'text') else response.candidates[0].content.parts[0].text

def debug_code(code: str):
    prompt = (
        "You are a Python code debugging assistant.\n\n"
        "Analyze the following code:\n"
        f"```python\n{code}\n```\n\n"
        "Please explain:\n"
        "- Any errors or bugs\n"
        "- Logical issues\n"
        "- Suggested improvements\n"
        "- Time and space complexity (if applicable)"
    )

    response = model.generate_content(prompt)

    return response.text if hasattr(response, 'text') else response.candidates[0].content.parts[0].text